### ISSUE TITLE
cookie required

### ISSUE THREAD

**Issue by jamesli2021** [withastro/studio-issues#10]
After connect to GitHub.

```
{"message":"\"githubOauthReturnTo\" cookie is required"}
```

**Comment by Princesseuh** [comment]
Duplicate of https://github.com/withastro/studio-issues/issues/8

**Comment by matthewp** [comment]
Thanks, which browser are you using?

**Comment by matthewp** [comment]
Were you using incognito mode by any chance?

**Comment by jamesli2021** [comment]
I use safari and firefox on macOS, not incognito mode.
