### ISSUE TITLE
Stackblitz does not work for private repos

### ISSUE THREAD

**Issue by goulvenclech** [withastro/studio-issues#11]
Stackblitz does not work for private repos, which is not very surprising, but I think you could disable the button or provide better information in this case 🙂

<img width="1004" alt="image" src="https://github.com/withastro/studio-issues/assets/35667800/41d52faa-9a8c-4fe8-a2bd-48d74556e9b2">

**Comment by fflaten** [comment]
Works if you use signin using Github in Stackblitz (top right corner) + install the Stackblitz app in the repo.

**Comment by snide** [comment]
Yep, I don't think this has to do with private vs. public. It's just that you need to install stackblitz separately and login.

**Comment by itsMapleLeaf** [comment]
Trying this myself, StackBlitz gives a good message asking you to install their GitHub app to see private repos, so I think we're good on this front
