### ISSUE TITLE
 Unable to save settings and duplicate project creation in the studio

### ISSUE THREAD

**Issue by anishshobithps** [withastro/studio-issues#14]
When trying to save settings in the studio, the changes are not being persisted, and the settings revert to their previous state upon refreshing the page or reopening the studio. 

Additionally, a duplicate project is being created sometimes.

Steps to reproduce:
1. Go to the [Studio](https://studio.astro.build/)
2. Start a Project
3. Import from GitHub
4. Selected a Astro website or template
5. While the process is ongoing just go to settings or other page
6. Come back you will find process is done. (Not sure if it is running on the background).
7. Go to the settings and add website URL and keep changing the name its, it throws errors saying unable to save.

Doing the Step 7 few more times will automatically create a duplicate file.

Other stuffs:
Region Uses: Asia (India)

Video : https://www.youtube.com/watch?v=Sqhd6wG9QQQ

**Comment by itsMapleLeaf** [comment]
We've made some updates and improvements to the project creation flow that should resolve this. Let us know if you're still running into it!
