### ISSUE TITLE
"Add Credit Card" at first login doesn't work (Stripe error)

### ISSUE THREAD

**Issue by goulvenclech** [withastro/studio-issues#2]
When I logged in for the first time, the button to add my card did not work.
![image](https://github.com/withastro/studio-issues/assets/35667800/9c582b78-3721-4bdb-ae0f-99ff76528aef)

I don't have this problem on the settings tab, but it still doesn't work, see #4

**Comment by matthewp** [comment]
Can you try again and let us know?

**Comment by goulvenclech** [comment]
@matthewp Sadly, I can't try again because this UI was on first log 🫤 but the #4 issue is fixed.
