### ISSUE TITLE
"Add Credit Card" from Settings does not work

### ISSUE THREAD

**Issue by goulvenclech** [withastro/studio-issues#4]
(May or may not be related to  #2 )

When I click on "Add a new card", fill the form, and submit. I am redirected (without any confirmation) to the home page. But sadly, my credit card wasn't saved, and Astro Studio still ask me to add a new card.
![image](https://github.com/withastro/studio-issues/assets/35667800/d937f25c-2f93-497b-8895-63b50040b31e)

**Comment by matthewp** [comment]
Can you try again and let us know?

**Comment by goulvenclech** [comment]
Well done @matthewp , it's fixed 😁
<img width="902" alt="image" src="https://github.com/withastro/studio-issues/assets/35667800/d00db74c-6364-4bcf-9004-61345f863081">

But I still think feedback (even just a pop-up on the home page) can be sweet.
