### ISSUE TITLE
"Connect your Github Account" does not work

### ISSUE THREAD

**Issue by goulvenclech** [withastro/studio-issues#5]
I'm stuck in a loop. After connecting Astro Studio with Github, here's what I got :

Step 1 - I click on "Connect your GitHub Account"
<img width="696" alt="image" src="https://github.com/withastro/studio-issues/assets/35667800/82e93522-8e7f-431c-b03f-f64cff86d344">

Step 2 - I click on "goulvenclech", my account which I already have connected.
<img width="552" alt="image" src="https://github.com/withastro/studio-issues/assets/35667800/016e8b7f-773b-40f1-909c-c7c4488e5bed">

Step 3 - I click on "save".
<img width="983" alt="image" src="https://github.com/withastro/studio-issues/assets/35667800/fa682409-1db1-47e3-ac9c-4a1f83d4f873">

Step 4 - I'm redirected to step 1.
<img width="708" alt="image" src="https://github.com/withastro/studio-issues/assets/35667800/e19291b7-b99f-4306-852b-5c51223700e7">

**Comment by akhdigital** [comment]
I was able to get this to work by going back Projects and creating an Empty Project. I was given an authorization request for Github and was then able to see my projects.

**Comment by goulvenclech** [comment]
Found a workaround, thanks to @aureliendossantos & @akhdigital :

1. Click on "new project".

2. Don't click on "Import from Github" but on "Create empty project".

3. Grant Github authorization.

4. Cancel empty project creation.

5. Back to "new project"

6. Click on "Import from Github"

<img width="711" alt="image" src="https://github.com/withastro/studio-issues/assets/35667800/7731adfc-b207-4cd6-9d2f-95fbee004286">

**Comment by matthewp** [comment]
We're in the process of fixing this. Thanks for the report!

**Comment by matthewp** [comment]
This should be fixed if you wouldn't mind retrying.

**Comment by goulvenclech** [comment]
Sorry @matthewp , can't try because we used the workaround to ignore this bug 🙁 maybe someone else can confirm ?

**Comment by akhdigital** [comment]
@matthewp I removed my project and re-added it. Seems to be working as expected! Thanks for the quick fix!
