### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by ktym4a** [withastro/studio-issues#8]
When I click "Continue with GitHub", then I see that message.
```.json
{
    "message": "\"githubOauthReturnTo\" cookie is required"
}
```

<img width="1415" alt="Screenshot 2024-03-12 at 23 45 18" src="https://github.com/withastro/studio-issues/assets/51779800/b6de0a64-028a-4aa9-a29d-0eed4d461eb0">

**Comment by matthewp** [comment]
@ktym4a which browser are you using?

**Comment by ktym4a** [comment]
@matthewp I'm using arc browser.
To be honest, I was able to sign in at first.
Once I signed out then I can not sign in. ((I don't know if it's affecting or not).

**Comment by JoshuaKGoldberg** [comment]
I get this on all browsers I've tried: Chrome, Firefox, and Safari on Mac. It's never let me log in.

Looking at the network tab, `https://auth.services.astro.build/github/oauth-callback?code=...&state=...` _(redacted - can DM if needed)_ gives a 500 response with the `{"message":"\"githubOauthReturnTo\" cookie is required"}` payload.

**Comment by goulvenclech** [comment]
Got the same bug on Chrome : 
<img width="492" alt="image" src="https://github.com/withastro/studio-issues/assets/35667800/8d943d84-47cf-498e-a12b-8dccf555ea32">

And Safari :
<img width="794" alt="image" src="https://github.com/withastro/studio-issues/assets/35667800/f62037b1-39bd-4631-8237-5f088cc1f816">

And Firefox (in private navigation, because I don't want to lose my session) : 
<img width="505" alt="image" src="https://github.com/withastro/studio-issues/assets/35667800/f0fe8129-96b7-4fc4-b3f7-818a99a69dfa">

MacOs too.

**Comment by matthewp** [comment]
Think we've found the problem here, and working on fix.

**Comment by matthewp** [comment]
Can everyone try again? Should be fixed.

**Comment by ktym4a** [comment]
don't get this message,
```
{
    "message": "\"githubOauthReturnTo\" cookie is required"
}
```

but seems that still has some error.

<img width="657" alt="Screenshot 2024-03-13 at 00 10 31" src="https://github.com/withastro/studio-issues/assets/51779800/20bd511d-9fcc-457a-9fe0-7a990201cc0b">

**Comment by ktym4a** [comment]
when I reload then can see dashboard.

**Comment by ktym4a** [comment]
and I sign out again and sign in again, I no longer see this error.

> don't get this message,
> 
> ```
> {
>     "message": "\"githubOauthReturnTo\" cookie is required"
> }
> ```
> 
> but seems that still has some error.
> 
> <img alt="Screenshot 2024-03-13 at 00 10 31" width="657" src="https://private-user-images.githubusercontent.com/51779800/312173879-20bd511d-9fcc-457a-9fe0-7a990201cc0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNjM3ODEsIm5iZiI6MTcxMDI2MzQ4MSwicGF0aCI6Ii81MTc3OTgwMC8zMTIxNzM4NzktMjBiZDUxMWQtOWZjYy00NTdhLTlmZTAtN2E5OTAyMDFjYzBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEyVDE3MTEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNzE3NTAxNDA5MjUzYzdkMTg5NGQ4YmRlNmY3ZTFiNjRmZGM5MzIzYzJlMjE3MjRhMzMxNzg0ODdkMGFkNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dwlUYS3DxXPuVLwbtLN2CxphnMk_0YZ484-RkhvU_xo">

**Comment by matthewp** [comment]
Ok interesting. If anyone else can see a similar error please let us know.

**Comment by matthewp** [comment]
Think this has been solved. If anyone runs into login issues please file a new issue. Thanks!
